[package]
name = "task-scheduler-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.7.1"
prost = "0.13.1"
prost-types = "0.13.1"
thiserror = "1.0.63"
tokio = { version = "1.39.3", features = ["full"] }

[build-dependencies]
prost-build = "0.13.1"
